config/routes.rb
Rails.application.routes.draw do
  resources :stocks

end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :stock

  enum option_type: [:put, :call]

  def to_s
    "type: #{option_type}
stock: #{stock.name},
strike_price: #{strike_price},
contract_name: #{contract_name},
last: #{last},
bid: #{bid},
ask: #{ask},
change: #{change},
percent_change: #{percent_change},
volume: #{volume},
open_interest: #{open_interest},
implied_volatility: #{implied_volatility}"
  end
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :options

  def ticker=(value)
    write_attribute(:ticker, value.downcase)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update_attributes(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params[:stock].permit(:name, :ticker)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OptionTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label(:name, "Company Name") %>
    <%= f.text_field(:name) %>
    <br />
    <%= f.label(:ticker, "Ticker") %>
    <%= f.text_field(:ticker) %>
    <br />
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stocks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  Company Name: <%= @stock.name %>
  <br />
  Ticker: <%= @stock.ticker.upcase %>
</p>

<table>
    <tr>
        <th>
            Type
        </th>
        <th>
            Strike
        </th>
        <th>
            Contract Name
        </th>
        <th>
            Last
        </th>
        <th>
            Bid
        </th>
        <th>
            Ask
        </th>
        <th>
            Change
        </th>
        <th>
            Percent Change
        </th>
        <th>
            Volume
        </th>
        <th>
            Open Interest
        </th>
        <th>
            Implied Volatility
        </th>
        <th>
            Expiration
        </th>
    </tr>

    <% @stock.options.all.each do |option| %>
    <tr>
        <td>
            <%= "#{option.option_type}" %>
        </td>
        <td>
            <%= "#{option.strike_price}" %>
        </td>
        <td>
            <%= "#{option.contract_name}" %>
        </td>
        <td>
            <%= "#{option.last}" %>
        </td>
        <td>
            <%= "#{option.bid}" %>
        </td>
        <td>
            <%= "#{option.ask}" %>
        </td>
        <td>
            <%= "#{option.change}" %>
        </td>
        <td>
            <%= "#{option.percent_change}" %>
        </td>
        <td>
            <%= "#{option.volume}" %>
        </td>
        <td>
            <%= "#{option.open_interest}" %>
        </td>
        <td>
            <%= "#{option.implied_volatility}" %>
        </td>
        <td>
            <%= "#{Time.at(option.expiration_time_seconds).gmtime.strftime("%Y-%b-%-d")}" %>
        </td>
    </tr>
<% end %>

</table>


  <br />

  <%= link_to 'Edit', edit_stock_path(@stock) %> |
  <%= link_to 'Back', stocks_path %>